import onionimg from "@/assets/onionimg.jpg";
import garlicimg from "@/assets/garlicimg1.webp";
import tomatoimg from "@/assets/tomatoimg.webp";
import beetrootimg from "@/assets/beetimg.jpg";
import spinachimg from "@/assets/spinachimg.png";
import gingerimg from "@/assets/ginger.png";
import mangopowderimg from "@/assets/alpmangoimg.jpg";
import bananaimg from "@/assets/bananaimg.webp";
import pomegranateimg from "@/assets/pomegranateimg.jpg";
import lemonimg from "@/assets/lemonimg.webp";
import orangepeelimg from "@/assets/orange.png";
import pineappleimg from "@/assets/pineapple.png";
import carrotimg from "@/assets/carrot.png"
import amlaimg from "@/assets/amla.png";
import moringaimg from "@/assets/moringa.png";
import turmericimg from "@/assets/turmeric.png";
import pumpkinimg from "@/assets/pumpkin.png";
import capsicumimg from "@/assets/capsicum.png";
import mushroomimg from "@/assets/mushroom.png";
import cabbageimg from "@/assets/cabbage.png";
import corianderleafimg from "@/assets/corianderleaf.png";
import mintimg from "@/assets/mint.png";
import ashwagandhaimg from "@/assets/ashwagandha.png";
import tamarindimg from "@/assets/tamarind.png";
import guavaimg from "@/assets/guava.png";
import jamunimg from "@/assets/jamun.png";
import coconutimg from "@/assets/coconut.png";
import strawberryimg from "@/assets/onionimg.jpg";
import blueberryimg from "@/assets/onionimg.jpg";
export const VEGETABLE_POWDERS = [
  {
    id: 1,
    name: "Onion Powder",
    slug: "onion-powder",
    type: "vegetable",
    category: "allium",
    taste: "pungent savory",
    aroma: "strong onion",
    color: "off white",
    meshSize: "80 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["seasoning", "soups", "snacks", "sauces", "instant noodles"],
    benefit: "Concentrated onion flavor for industrial food processing.",
    description: "Export-grade dehydrated onion powder for seasoning blends, instant soups, and sauce manufacturing.",
    cert: ["natural", "fssc22000", "haccp"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "Mesh 80",
    image: onionimg.src,
    featured: true,
    desc: "Fine dehydrated onion powder for seasoning blends and industrial food applications.",
  },
  {
    id: 2,
    name: "Garlic Powder",
    slug: "garlic-powder",
    type: "vegetable",
    category: "allium",
    taste: "pungent sharp",
    aroma: "strong garlic",
    color: "cream white",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["seasoning", "marinades", "snack coatings", "ready meals"],
    benefit: "Intense garlic flavor with long shelf life.",
    description: "Premium dehydrated garlic powder for food manufacturing and export supply.",
    cert: ["natural", "fssc22000"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "Premium Grade",
    image: garlicimg.src,
    desc: "Strong aromatic garlic powder with rich pungent flavor for seasoning and sauce production.",
  },
  {
    id: 3,
    name: "Tomato Powder",
    slug: "tomato-powder",
    type: "vegetable",
    category: "fruit-veg",
    taste: "tangy sweet",
    aroma: "fresh tomato",
    color: "bright red",
    meshSize: "80 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["soups", "sauces", "seasoning", "ketchup base", "instant mixes"],
    benefit: "Natural color and flavor for food manufacturing.",
    description: "Spray-dried tomato powder with vibrant color for soups, sauces, and food manufacturing.",
    cert: ["natural", "fssc22000"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Natural Color",
    image: tomatoimg.src,
    desc: "Bright red tomato powder for soups, sauces, and industrial food color applications.",
  },
  {
    id: 4,
    name: "Beetroot Powder",
    slug: "beetroot-powder",
    type: "vegetable",
    category: "root",
    taste: "earthy sweet",
    aroma: "mild earthy",
    color: "deep red purple",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["natural coloring", "health drinks", "nutraceuticals", "bakery"],
    benefit: "Natural red colorant and high nitrate content.",
    description: "Vibrant spray-dried beetroot powder for natural food coloring and nutraceutical applications.",
    cert: ["organic", "natural"],
    shelfLife: "18 months",
    storage: "cool dry airtight container",
    badge: "Fine Mesh",
    image: beetrootimg.src,
    desc: "Vibrant beetroot powder for natural food coloring, health drinks, and supplement formulations.",
  },
  {
    id: 5,
    name: "Spinach Powder",
    slug: "spinach-powder",
    type: "vegetable",
    category: "leafy",
    taste: "mild vegetal",
    aroma: "fresh greens",
    color: "dark green",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["health drinks", "nutraceuticals", "pasta", "bakery fortification"],
    benefit: "High iron, folate, and chlorophyll content.",
    description: "Nutritious spinach powder for green smoothies, pasta manufacturing, and health supplement blends.",
    cert: ["organic", "natural"],
    shelfLife: "18 months",
    storage: "cool dry airtight container",
    badge: "Nutrient Dense",
    image: spinachimg.src,
    desc: "Dark green spinach powder rich in iron and nutrients for health drink and supplement formulations.",
  },
  {
    id: 6,
    name: "Ginger Powder",
    slug: "ginger-powder",
    type: "vegetable",
    category: "spice-root",
    taste: "spicy warm",
    aroma: "strong ginger",
    color: "pale yellow",
    meshSize: "80 mesh",
    moistureContent: "≤ 8%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["seasoning", "tea", "health drinks", "bakery", "marinades"],
    benefit: "High gingerol content with anti-inflammatory properties.",
    description: "Pungent dehydrated ginger powder retaining bioactive compounds for food and beverage manufacturing.",
    cert: ["organic", "natural"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "High Gingerol",
    image: gingerimg.src,
    desc: "Intense ginger powder with preserved bioactive gingerols for seasoning and health formulations.",
  },
  {
    id: 7,
    name: "Carrot Powder",
    slug: "carrot-powder",
    type: "vegetable",
    category: "root",
    taste: "mild sweet",
    aroma: "fresh carrot",
    color: "orange",
    meshSize: "80 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["baby food", "soups", "juices", "health mixes"],
    benefit: "Rich in beta-carotene and natural orange color.",
    description: "Spray-dried carrot powder rich in beta-carotene for baby food, juices, and health formulations.",
    cert: ["natural", "organic"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Beta-Carotene Rich",
    image: carrotimg.src,
    desc: "Natural orange carrot powder high in beta-carotene for baby food, soups, and fortified beverages.",
  },
  {
    id: 8,
    name: "Amla Powder",
    slug: "amla-powder",
    type: "vegetable",
    category: "ayurvedic",
    taste: "sour astringent",
    aroma: "tangy herbal",
    color: "light green brown",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 8%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["nutraceuticals", "health supplements", "hair care", "ayurveda"],
    benefit: "Highest natural Vitamin C source.",
    description: "Traditional Indian gooseberry powder with exceptional vitamin C content for nutraceutical export.",
    cert: ["organic", "natural"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "Vitamin C Rich",
    image: amlaimg.src,
    desc: "High Vitamin C amla powder for immunity supplements and Ayurvedic health formulations.",
  },
  {
    id: 9,
    name: "Moringa Powder",
    slug: "moringa-powder",
    type: "vegetable",
    category: "superfood",
    taste: "mild grassy",
    aroma: "fresh herbal",
    color: "bright green",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "shade drying + milling",
    origin: "India",
    use: ["nutraceuticals", "health drinks", "protein blends", "supplements"],
    benefit: "Complete amino acid profile and high micronutrient density.",
    description: "Shade-dried moringa leaf powder for premium nutraceutical and wellness product manufacturing.",
    cert: ["organic", "natural"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "Superfood",
    image: moringaimg.src,
    desc: "Nutrient-dense moringa leaf powder for superfoods, health supplements, and protein formulations.",
  },
  {
    id: 10,
    name: "Turmeric Powder",
    slug: "turmeric-powder",
    type: "vegetable",
    category: "spice-root",
    taste: "bitter warm",
    aroma: "earthy spicy",
    color: "bright yellow",
    meshSize: "80 mesh",
    moistureContent: "≤ 8%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["seasoning", "curries", "supplements", "food coloring"],
    benefit: "High curcumin content for anti-inflammatory applications.",
    description: "High-curcumin turmeric powder for food manufacturing, nutraceutical, and natural coloring export.",
    cert: ["organic", "natural", "fssc22000"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "High Curcumin",
    image: turmericimg.src,
    desc: "Vibrant yellow turmeric powder with high curcumin content for seasoning and supplement applications.",
  },
  {
    id: 11,
    name: "Pumpkin Powder",
    slug: "pumpkin-powder",
    type: "vegetable",
    category: "gourd",
    taste: "mild sweet",
    aroma: "earthy pumpkin",
    color: "golden yellow",
    meshSize: "80 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["soups", "baby food", "bakery", "health mixes"],
    benefit: "Rich in fiber and beta-carotene.",
    description: "Dehydrated pumpkin processed into smooth nutrient-rich powder.",
    cert: ["natural", "organic"],
    shelfLife: "18 months",
    storage: "cool dry airtight container",
    badge: "Fiber Rich",
    image: pumpkinimg.src,
    desc: "Smooth golden pumpkin powder for baby food, soups, and bakery fortification.",
  },
  {
    id: 12,
    name: "Capsicum Powder",
    slug: "capsicum-powder",
    type: "vegetable",
    category: "spice",
    taste: "sweet peppery",
    aroma: "fresh capsicum",
    color: "bright red",
    meshSize: "80 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration",
    origin: "India",
    use: ["seasoning", "snacks", "sauces", "soups"],
    benefit: "Adds natural color and mild pepper flavor.",
    description: "Dehydrated capsicum ground into vibrant powder for seasoning and coloring applications.",
    cert: ["natural"],
    shelfLife: "12 months",
    storage: "cool dry place",
    badge: "Natural Flavor",
    image: capsicumimg.src,
    desc: "Vibrant red capsicum powder for natural coloring, seasoning blends, and snack coatings.",
  },
  {
    id: 13,
    name: "Mushroom Powder",
    slug: "mushroom-powder",
    type: "vegetable",
    category: "fungi",
    taste: "umami savory",
    aroma: "earthy mushroom",
    color: "light brown",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["soups", "seasoning", "gravies", "health foods"],
    benefit: "Adds natural umami and nutrients.",
    description: "Dehydrated mushrooms finely milled into savory powder for soups and seasoning applications.",
    cert: ["natural"],
    shelfLife: "18 months",
    storage: "airtight dry container",
    badge: "Umami Rich",
    image: mushroomimg.src,
    desc: "Savory mushroom powder adding natural umami flavor to soups, gravies, and seasoning blends.",
  },
  {
    id: 14,
    name: "Cabbage Powder",
    slug: "cabbage-powder",
    type: "vegetable",
    category: "leafy",
    taste: "mild vegetal",
    aroma: "fresh cabbage",
    color: "light green",
    meshSize: "80 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["soups", "health foods", "seasoning"],
    benefit: "Provides fiber and vegetable nutrients.",
    description: "Dehydrated cabbage finely processed into powder for soups and health food applications.",
    cert: ["natural"],
    shelfLife: "12 months",
    storage: "airtight container",
    badge: "Leafy Nutrition",
    image: cabbageimg.src,
    desc: "Fine cabbage powder for instant soups, health food blends, and vegetable seasoning applications.",
  },
  {
    id: 15,
    name: "Coriander Leaf Powder",
    slug: "coriander-leaf-powder",
    type: "vegetable",
    category: "herb",
    taste: "fresh herbal",
    aroma: "coriander leafy",
    color: "green",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "shade drying + milling",
    origin: "India",
    use: ["curries", "soups", "seasoning blends"],
    benefit: "Adds fresh herb flavor year-round.",
    description: "Shade-dried coriander leaves ground into aromatic powder for curries and seasoning blends.",
    cert: ["natural", "organic"],
    shelfLife: "12 months",
    storage: "cool dry airtight container",
    badge: "Fresh Herb",
    image: corianderleafimg.src,
    desc: "Aromatic coriander leaf powder for curries, seasoning blends, and instant food formulations.",
  },
  {
    id: 16,
    name: "Mint Powder",
    slug: "mint-powder",
    type: "vegetable",
    category: "herb",
    taste: "cool refreshing",
    aroma: "minty fresh",
    color: "green",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "shade drying",
    origin: "India",
    use: ["tea", "seasoning", "health drinks", "chutneys"],
    benefit: "Provides refreshing flavor and digestive support.",
    description: "Dried mint leaves finely powdered for tea blends, health drinks, and seasoning applications.",
    cert: ["organic", "natural"],
    shelfLife: "12 months",
    storage: "airtight cool container",
    badge: "Refreshing Herb",
    image: mintimg.src,
    desc: "Cool refreshing mint powder for tea manufacturing, health drinks, and chutney formulations.",
  },
  {
    id: 17,
    name: "Ashwagandha Powder",
    slug: "ashwagandha-powder",
    type: "vegetable",
    category: "ayurvedic",
    taste: "bitter earthy",
    aroma: "herbal earthy",
    color: "pale yellow brown",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 8%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "root drying + milling",
    origin: "India",
    use: ["nutraceuticals", "stress supplements", "ayurveda", "protein blends"],
    benefit: "Adaptogenic properties for stress and immunity support.",
    description: "Export-grade ashwagandha root powder for nutraceutical and wellness supplement manufacturing.",
    cert: ["organic", "natural"],
    shelfLife: "24 months",
    storage: "cool dry airtight container",
    badge: "Adaptogen",
    image: ashwagandhaimg.src,
    desc: "Premium ashwagandha root powder for stress management supplements and Ayurvedic formulations.",
  },
];

export const FRUIT_POWDERS = [
  {
    id: 1,
    name: "Mango Powder",
    slug: "mango-powder",
    type: "fruit",
    category: "tropical",
    taste: "sweet",
    aroma: "ripe mango",
    color: "golden yellow",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "spray-dried powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["beverage", "dessert", "smoothies", "bakery", "nutraceuticals"],
    cert: ["organic", "fssc22000"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Tropical Bestseller",
    image: mangopowderimg.src,
    desc: "Premium spray-dried Alphonso mango powder for desserts, beverages, and nutraceutical applications.",
    featured: true,
    benefit: "Naturally sweet with high Vitamin A and C content.",
    description: "Export-grade spray-dried mango powder made from premium Alphonso mangoes for global food manufacturers.",
  },
  {
    id: 2,
    name: "Banana Powder",
    slug: "banana-powder",
    type: "fruit",
    category: "tropical",
    taste: "sweet mild",
    aroma: "soft banana",
    color: "cream",
    meshSize: "80 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration",
    origin: "India",
    use: ["baby food", "smoothies", "baking", "protein blends"],
    cert: ["natural"],
    shelfLife: "18 months",
    storage: "airtight container",
    badge: "Energy Rich",
    image: bananaimg.src,
    desc: "Creamy banana powder ideal for baby nutrition, protein shakes, and bakery blends.",
    benefit: "High potassium and natural sugar content.",
    description: "Dehydrated banana powder for baby food manufacturing, protein shake formulations, and bakery applications.",
  },
  {
    id: 3,
    name: "Pomegranate Powder",
    slug: "pomegranate-powder",
    type: "fruit",
    category: "berry",
    taste: "tangy sweet",
    aroma: "berry fresh",
    color: "deep red",
    meshSize: "100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "spray-dried powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["health drinks", "smoothies", "nutraceuticals", "supplements"],
    cert: ["organic"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Antioxidant Rich",
    image: pomegranateimg.src,
    desc: "High antioxidant pomegranate powder for wellness drinks and nutraceutical supplement manufacturing.",
    benefit: "Highest ORAC antioxidant value among common fruits.",
    description: "Spray-dried pomegranate powder with exceptional antioxidant profile for nutraceutical and beverage export.",
  },
  {
    id: 4,
    name: "Lemon Powder",
    slug: "lemon-powder",
    type: "fruit",
    category: "citrus",
    taste: "sour",
    aroma: "sharp citrus",
    color: "pale yellow",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["beverages", "seasoning", "desserts", "instant drink mixes"],
    cert: ["natural"],
    shelfLife: "12–18 months",
    storage: "airtight container",
    badge: "Zesty Flavor",
    image: lemonimg.src,
    desc: "Natural citrus lemon powder for instant souring in beverages, seasoning, and dessert applications.",
    benefit: "High Vitamin C and natural citric acid content.",
    description: "Dehydrated lemon powder for instant beverage mixes, seasoning applications, and food manufacturing.",
  },
  {
    id: 5,
    name: "Orange Peel Powder",
    slug: "orange-peel-powder",
    type: "fruit",
    category: "citrus",
    taste: "bitter sweet",
    aroma: "strong citrus",
    color: "orange",
    meshSize: "60–80 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "ground powder",
    processingMethod: "sun-dried + milling",
    origin: "India",
    use: ["tea", "baking", "flavoring", "nutraceuticals"],
    cert: ["natural"],
    shelfLife: "18 months",
    storage: "dry container",
    badge: "Aromatic Peel",
    image: orangepeelimg.src,
    desc: "Aromatic orange peel powder for tea blends, bakery applications, and natural flavoring systems.",
    benefit: "High bioflavonoids and natural aromatic compounds.",
    description: "Sun-dried orange peel powder for tea manufacturing, bakery flavoring, and nutraceutical applications.",
  },
  {
    id: 6,
    name: "Pineapple Powder",
    slug: "pineapple-powder",
    type: "fruit",
    category: "tropical",
    taste: "sweet tangy",
    aroma: "fresh pineapple",
    color: "yellow",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "spray-dried powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["smoothies", "desserts", "beverages", "enzyme supplements"],
    cert: ["organic"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Tropical Enzyme",
    image: pineappleimg.src,
    desc: "Enzyme-rich spray-dried pineapple powder for digestion-friendly beverage and supplement formulations.",
    benefit: "Natural bromelain enzyme content.",
    description: "Spray-dried pineapple powder retaining natural bromelain enzyme for health and beverage manufacturing.",
  },
  {
    id: 7,
    name: "Coconut Milk Powder",
    slug: "coconut-milk-powder",
    type: "fruit",
    category: "tropical-fat",
    taste: "creamy",
    aroma: "rich coconut",
    color: "white cream",
    meshSize: "80 mesh",
    moistureContent: "≤ 4%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "spray-dried fat powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["curries", "desserts", "beverages", "dairy-free products"],
    cert: ["natural"],
    shelfLife: "12–18 months",
    storage: "cool dry place",
    badge: "Dairy Alternative",
    image: coconutimg.src,
    desc: "Rich coconut milk powder for dairy-free product manufacturing, curries, and dessert applications.",
    benefit: "Natural medium-chain triglycerides and creamy texture.",
    description: "Spray-dried coconut milk powder as dairy-free ingredient for food manufacturers globally.",
  },
  {
    id: 8,
    name: "Tamarind Powder",
    slug: "tamarind-powder",
    type: "fruit",
    category: "tangy",
    taste: "sour",
    aroma: "deep tangy",
    color: "dark brown",
    meshSize: "60–80 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "ground powder",
    processingMethod: "dehydration",
    origin: "India",
    use: ["curries", "chutneys", "snacks", "sauces"],
    cert: ["natural"],
    shelfLife: "18 months",
    storage: "airtight container",
    badge: "Sour Enhancer",
    image: tamarindimg.src,
    desc: "Natural souring agent tamarind powder for curry pastes, chutneys, and snack seasoning applications.",
    benefit: "Natural tartaric acid for consistent souring.",
    description: "Dehydrated tamarind powder for natural souring in traditional and modern food manufacturing.",
  },
  {
    id: 9,
    name: "Guava Powder",
    slug: "guava-powder",
    type: "fruit",
    category: "tropical",
    taste: "sweet floral",
    aroma: "fresh guava",
    color: "pinkish",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 5%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "spray-dried powder",
    processingMethod: "spray drying",
    origin: "India",
    use: ["smoothies", "health drinks", "supplements", "nutraceuticals"],
    cert: ["organic"],
    shelfLife: "18 months",
    storage: "cool dry place",
    badge: "Vitamin C Rich",
    image: guavaimg.src,
    desc: "High Vitamin C guava powder for immunity supplement formulations and health beverage manufacturing.",
    benefit: "Exceptionally high Vitamin C content.",
    description: "Spray-dried guava powder with exceptional Vitamin C content for immunity supplement export.",
  },
  {
    id: 10,
    name: "Jamun Powder",
    slug: "jamun-powder",
    type: "fruit",
    category: "berry",
    taste: "sweet astringent",
    aroma: "earthy berry",
    color: "deep purple",
    meshSize: "80–100 mesh",
    moistureContent: "≤ 6%",
    packaging: ["25kg bags", "50kg bags", "custom bulk"],
    form: "fine powder",
    processingMethod: "dehydration + milling",
    origin: "India",
    use: ["health drinks", "supplements", "diabetic support", "ayurveda"],
    cert: ["natural"],
    shelfLife: "18 months",
    storage: "airtight container",
    badge: "Ayurvedic Fruit",
    image: jamunimg.src,
    desc: "Traditional Jamun (Indian blackberry) powder for wellness and diabetic-support supplement formulations.",
    benefit: "Traditional glycemic management and antioxidant properties.",
    description: "Dehydrated Jamun powder for nutraceutical, Ayurvedic, and diabetic wellness product manufacturing.",
  },
];
